# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %HAXELIB_ROOT%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c

      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          lime setup android
          Run lime setup android
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install linc_luajit
          haxelib install hscript
          haxelib install polymod
          haxelib update polymod
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install hxcpp-debug-server
          haxelib list
          
      - name: Build Log
        run: |
          haxelib run lime setup android
          haxelib run lime build android -final
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug
